import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';

import '../../../core/theme/app_colors.dart';
import '../../../core/widgets/app_button.dart';
import '../../../core/widgets/app_text_field.dart';
import '../../../core/widgets/error_view.dart';
import '../../../core/widgets/loading_indicator.dart';
import '../data/admin_repository.dart';
import '../domain/department_official_detail.dart';

/// Admin-only create/edit form for a department official. `officialId ==
/// null` is create mode (asks for a login password only -- login email and
/// employee reference are auto-generated by `admin_create_department_official`
/// from first/last name and the selected department's domain, overridable
/// via the optional fields); otherwise it's edit mode (profile fields only
/// -- no email/password change here, kept out of scope).
class DepartmentOfficialFormScreen extends ConsumerStatefulWidget {
  const DepartmentOfficialFormScreen({super.key, this.officialId});

  final String? officialId;

  bool get isEdit => officialId != null;

  @override
  ConsumerState<DepartmentOfficialFormScreen> createState() => _DepartmentOfficialFormScreenState();
}

class _DepartmentOfficialFormScreenState extends ConsumerState<DepartmentOfficialFormScreen> {
  final _formKey = GlobalKey<FormState>();
  final _firstNameController = TextEditingController();
  final _lastNameController = TextEditingController();
  final _emailOverrideController = TextEditingController();
  final _passwordController = TextEditingController();
  final _roleController = TextEditingController();
  final _employeeRefController = TextEditingController();

  String? _departmentId;
  bool _prefilled = false;
  bool _submitting = false;
  String? _error;

  @override
  void dispose() {
    _firstNameController.dispose();
    _lastNameController.dispose();
    _emailOverrideController.dispose();
    _passwordController.dispose();
    _roleController.dispose();
    _employeeRefController.dispose();
    super.dispose();
  }

  void _prefillIfNeeded(DepartmentOfficialDetail? detail) {
    if (_prefilled || detail == null) return;
    _prefilled = true;
    _firstNameController.text = detail.firstName;
    _lastNameController.text = detail.lastName;
    _roleController.text = detail.officialRole;
    _employeeRefController.text = detail.employeeReference ?? '';
    _departmentId = detail.departmentId;
  }

  Future<void> _submit() async {
    if (!(_formKey.currentState?.validate() ?? false)) return;
    if (_departmentId == null) {
      setState(() => _error = 'Select a department.');
      return;
    }

    setState(() {
      _submitting = true;
      _error = null;
    });

    try {
      final repo = ref.read(adminRepositoryProvider);
      if (widget.isEdit) {
        await repo.updateDepartmentOfficial(
          officialId: widget.officialId!,
          firstName: _firstNameController.text.trim(),
          lastName: _lastNameController.text.trim(),
          officialRole: _roleController.text.trim(),
          departmentId: _departmentId!,
          employeeReference: _employeeRefController.text.trim(),
        );
      } else {
        await repo.createDepartmentOfficial(
          firstName: _firstNameController.text.trim(),
          lastName: _lastNameController.text.trim(),
          password: _passwordController.text,
          officialRole: _roleController.text.trim(),
          departmentId: _departmentId!,
          employeeReference: _employeeRefController.text.trim(),
          email: _emailOverrideController.text.trim(),
        );
      }
      ref.invalidate(adminUsersProvider);
      ref.invalidate(adminDepartmentsProvider);
      if (widget.isEdit) ref.invalidate(departmentOfficialDetailProvider(widget.officialId!));
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text(widget.isEdit ? 'Official updated.' : 'Official created.')),
        );
        context.pop();
      }
    } catch (e) {
      setState(() => _error = 'Could not save this official: $e');
    } finally {
      if (mounted) setState(() => _submitting = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final departmentsAsync = ref.watch(adminDepartmentsProvider);
    final detailAsync = widget.isEdit
        ? ref.watch(departmentOfficialDetailProvider(widget.officialId!))
        : null;

    if (widget.isEdit) {
      if (detailAsync!.isLoading) {
        return Scaffold(appBar: AppBar(title: const Text('Edit Official')), body: const LoadingIndicator());
      }
      if (detailAsync.hasError) {
        return Scaffold(
          appBar: AppBar(title: const Text('Edit Official')),
          body: const ErrorView(message: 'Could not load this official.'),
        );
      }
      _prefillIfNeeded(detailAsync.value);
    }

    return Scaffold(
      appBar: AppBar(title: Text(widget.isEdit ? 'Edit Official' : 'Add Official')),
      body: SafeArea(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(24),
          child: Form(
            key: _formKey,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                AppTextField(
                  label: 'First name',
                  controller: _firstNameController,
                  prefixIcon: Icons.person_outline,
                  validator: (v) => (v == null || v.trim().isEmpty) ? 'Enter a first name' : null,
                ),
                const SizedBox(height: 14),
                AppTextField(
                  label: 'Surname',
                  controller: _lastNameController,
                  prefixIcon: Icons.person_outline,
                  validator: (v) => (v == null || v.trim().isEmpty) ? 'Enter a surname' : null,
                ),
                const SizedBox(height: 14),
                if (!widget.isEdit) ...[
                  AppTextField(
                    label: 'Password',
                    controller: _passwordController,
                    obscureText: true,
                    prefixIcon: Icons.lock_outline,
                    validator: (v) =>
                        (v == null || v.length < 6) ? 'Enter a password (6+ characters)' : null,
                  ),
                  const SizedBox(height: 14),
                  AppTextField(
                    label: 'Login email (optional -- auto-generated as name.surname@department)',
                    controller: _emailOverrideController,
                    keyboardType: TextInputType.emailAddress,
                    prefixIcon: Icons.mail_outline,
                  ),
                  const SizedBox(height: 14),
                ],
                AppTextField(
                  label: 'Job title / role',
                  controller: _roleController,
                  prefixIcon: Icons.work_outline,
                  validator: (v) => (v == null || v.trim().isEmpty) ? 'Enter a job title' : null,
                ),
                const SizedBox(height: 14),
                departmentsAsync.when(
                  loading: () => const LoadingIndicator(),
                  error: (e, _) => const Text('Could not load departments.'),
                  data: (departments) => DropdownButtonFormField<String>(
                    initialValue: _departmentId,
                    decoration: const InputDecoration(
                      labelText: 'Department',
                      prefixIcon: Icon(Icons.account_balance_outlined),
                    ),
                    items: [
                      for (final d in departments)
                        DropdownMenuItem(
                          value: d.departmentId,
                          child: Text(d.active ? d.departmentName : '${d.departmentName} (inactive)'),
                        ),
                    ],
                    onChanged: (v) => setState(() => _departmentId = v),
                    validator: (v) => v == null ? 'Select a department' : null,
                  ),
                ),
                const SizedBox(height: 14),
                AppTextField(
                  label: widget.isEdit
                      ? 'Employee reference'
                      : 'Employee reference (optional -- auto-generated)',
                  controller: _employeeRefController,
                  prefixIcon: Icons.badge_outlined,
                ),
                if (_error != null) ...[
                  const SizedBox(height: 12),
                  Text(_error!, style: const TextStyle(color: AppColors.error, fontSize: 13)),
                ],
                const SizedBox(height: 20),
                AppButton(
                  label: widget.isEdit ? 'Save changes' : 'Create official',
                  icon: widget.isEdit ? Icons.save_outlined : Icons.person_add_alt_outlined,
                  loading: _submitting,
                  expand: true,
                  onPressed: _submit,
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
